---
title: "Course Syllabus"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  comment = "")
```

Last Updated: `r format(Sys.Date(), "%m/%d/%Y")`

# Course Title {#title}

PSY 3330 – Childhood Psychopathology (Fall 2023)

# Course Meeting Time and Place {#lectureTime}

Monday, Wednesday, & Friday 10:30–11:20 a.m., 158 Van Allen (VAN)

# Course Website {#website}

https://icon.uiowa.edu

To access the course site, log into [Iowa Courses Online (ICON)](https://icon.uiowa.edu) using your Hawk ID and password.

# Course Home {#home}

The College of Liberal Arts and Sciences (CLAS) is the home of this course, and CLAS governs the add and drop deadlines, the "second-grade only" option (SGO), academic misconduct policies, and other policies and procedures.
Other UI colleges may have different policies.

# Instructor {#instructor}

[Professor Petersen](https://psychology.uiowa.edu/people/isaac-petersen)\
Office: 175 Psychological and Brain Sciences Building (PBSB)\
E-mail: [isaac-t-petersen@uiowa.edu](mailto:isaac-t-petersen@uiowa.edu)\
Office Phone: 467-1014\
Student drop-in hours: Monday 11:20–12:20 & Wednesday 2–4\
Note: I'm here to help you learn and succeed.
Please come to my office hours to ask questions about course material, assignments, exams, or professional development (career-related issues), for instance.
I welcome you to discuss any concerns you might have about the class.
I am also available to meet with you by appointment, although I would appreciate your making every effort to see me during office hours.
The best way to reach me outside of class is by email.

# Graduate Teaching Assistant {#TA}

The class has one graduate teaching assistant (TA).

Ariel Kim\
Office: 255H Psychological and Brain Sciences Building (PBSB)—ring the bell at 255W, and she will let you in\
Student drop-in hours: Wednesday 11:20–12:20 & Friday 1:10–2:10\
E-mail: nam-yoon-kim@uiowa.edu

# Departmental Resources {#deptResources}

Department of Psychological and Brain Sciences: [https://psychology.uiowa.edu](https://psychology.uiowa.edu)\
Department of Psychological and Brain Sciences Main Office: G60 Psychological and Brain Sciences Building (335-2406)\
Coordinator of Undergraduate Studies: Professor Windschitl ([paul-windschitl@uiowa.edu](mailto:paul-windschitl@uiowa.edu); 335-3681)\
Academic Coordinator: Professor Johnson ([debra-johnson@uiowa.edu](mailto:debra-johnson@uiowa.edu); 335-0135)\
Chair of Department: Professor Blumberg ([mark-blumberg@uiowa.edu](mailto:mark-blumberg@uiowa.edu); 335-2424)

# Prerequisites {#prereqs}

The Department of Psychological and Brain Sciences has a hierarchical course structure that requires students to complete certain prerequisite courses before taking upper-level courses.
This course requires successful completion (C- or higher) of Elementary Psychology, Introduction to Clinical Psychology, and Research Methods in Psychology.
The department will check student records to ensure completion of course prerequisites.  

# Description of Course {#description}

This course satisfies the upper-level elective requirement for Psychological and Brain Sciences majors.
Additionally, students with broad interests in health and development will find this course useful. 
The goal of this course is to provide students with a comprehensive introduction to child and adolescent psychopathology.
This includes an emphasis on the developmental psychopathology framework and involves thinking critically about the causes, consequences, ongoing questions, and preventative challenges of child psychopathology facing scientists, youth and their families, clinicians, and society. 
We apply elements of the developmental psychopathology model to a range of childhood disorders. 
Within each syndrome, possible genetic, neurobiological, psychological, familial, and socio-cultural causal factors will be scrutinized.
We will also review and discuss risk and resilience factors for child psychopathology (individual, family, community) as well as models of treatment and prevention.
*You are urged to reconsider your decision to take this class if you are reluctant to examine these topics in a scientific manner.*

# Learning Objectives {#objectives}

At the end of this course, you will be able to:

- Identify the symptoms and course of psychological disorders in childhood.
- Distinguish the various risk factors that contribute to psychopathology in childhood.  
- Identify factors that may protect against the development of psychopathology and promote resilience.
- Describe different methods for treatment and prevention of psychological disorders in childhood.
- Critique, analyze, and synthesize original source articles in developmental psychopathology.
- Produce an APA-style literature review that integrates empirical findings in developmental psychopathology.

# Required Materials {#materials}

## Textbook {#textbook}

To provide you with a textbook for as low cost as possible, you will be provided an eText of the following book via ICON Direct, unless you opt out:

**Mash, E. J., Wolfe, D. A., & Williams, K. N. (2023). *Childhood psychopathology* (8th Ed.). Cengage.**

Your U-Bill will be charged automatically after your course has started, unless you [opt out](https://teach.uiowa.edu/icon-direct/opt-out) prior to the last day for tuition and fee reduction [course deadline](https://registrar.uiowa.edu/course-deadlines).
For frequently asked questions about ICON Direct, including how to access the eText, see [here](https://teach.uiowa.edu/icon-direct/student-frequently-asked-questions).
However, if you want to purchase a hardcopy of the textbook (for a higher cost) you may [opt out](https://teach.uiowa.edu/icon-direct/opt-out) of the eText via ICON Direct.
For instructions how to opt out of ICON Direct, see [here](https://teach.uiowa.edu/icon-direct/opt-out).
However, if you opt out, please note:

- You risk falling behind in the course if you have not acquired alternate versions of the same materials prior to the first day of the class.
- Instructors are not responsible for providing you with alternative materials or waiving course/class requirements.

## Articles {#articles}

In addition to the textbook, additional required readings for selected topics will include the following articles.
PDFs of these articles can be found on [ICON](https://icon.uiowa.edu).

1. Shea, S. E., Gordon, K., Hawkins, A., Kawchuk, J., & Smith, D. (2000). Pathology in the hundred acre wood: A neurodevelopmental perspective on A.A. Milne. *Canadian Medical Association Journal, 163*(12), 1557–1559. https://www.cmaj.ca/content/cmaj/163/12/1557.full.pdf (Just for fun! 😊)
1. Ra, C. K., Cho, J., Stone, M. D., De La Cerda, J., Goldenson, N. I., Moroney, E., Tung, I., Lee, S. S., & Leventhal, A. M. (2018). Association of digital media use with subsequent symptoms of attention-deficit/hyperactivity disorder among adolescents. *JAMA, 320*(3), 255–263. https://doi.org/10.1001/jama.2018.8931
1. Christakis, D. A., Zimmerman, F. J., DiGiuseppe, D. L., & McCarty, C. A. (2004). Early television exposure and subsequent attentional problems in children. *Pediatrics, 113*(4), 708–713. https://doi.org/10.1542/peds.113.4.708
1. Thapar, A., Rice, F., Hay, D., Boivin, J., Langley, K., van den Bree, M., Rutter, M., & Harold, G. (2009). Prenatal smoking might not cause attention-deficit/hyperactivity disorder: Evidence from a novel design. *Biological Psychiatry, 66*(8), 722–727. https://doi.org/10.1016/j.biopsych.2009.05.032
1. Ozonoff, S., Iosif, A.-M., Baguio, F., Cook, I. C., Hill, M. M., Hutman, T., Rogers, S. J., Rozga, A., Sangha, S., Sigman, M., Steinfeld, M. B., & Young, G. S. (2010). A prospective study of the emergence of early behavioral signs of autism. *Journal of the American Academy of Child & Adolescent Psychiatry, 49*(3), 256–266.e252. https://doi.org/10.1016/j.jaac.2009.11.009
1. Frick, P. J. (2012). Developmental pathways to conduct disorder: Implications for future directions in research, assessment, and treatment. *Journal of Clinical Child & Adolescent Psychology, 41*(3), 378–389. https://doi.org/10.1080/15374416.2012.664815
1. How to Write a Literature Review.
1. Kendall, P. C., Settipani, C. A., & Cummings, C. M. (2012). No need to worry: The promising future of child anxiety research. *Journal of Clinical Child & Adolescent Psychology, 41*(1), 103–115. https://doi.org/10.1080/15374416.2012.632352
1. Stringaris, A., Vidal-Ribas, P., Brotman, M. A., & Leibenluft, E. (2018). Practitioner Review: Definition, recognition, and treatment challenges of irritability in young people. *Journal of Child Psychology and Psychiatry, 59*(7), 721–739. https://doi.org/10.1111/jcpp.12823
1. Stice, E., South, K., & Shaw, H. (2012). Future directions in etiologic, prevention, and treatment research for eating disorders. *Journal of Clinical Child & Adolescent Psychology, 41*(6), 845–855. https://doi.org/10.1080/15374416.2012.728156
1. Young, R., Sproeber, N., Groschwitz, R. C., Preiss, M., & Plener, P. L. (2014). Why alternative teenagers self-harm: exploring the link between non-suicidal self-injury, attempted suicide and adolescent identity. *BMC Psychiatry, 14*(1), 137. https://doi.org/10.1186/1471-244X-14-137
1. Colvert, E., Rutter, M., Kreppner, J., Beckett, C., Castle, J., Groothues, C., Hawkins, A., Stevens, S., & Sonuga-Barke, E. J. S. (2008). Do theory of mind and executive function deficits underlie the adverse outcomes associated with profound early deprivation?: Findings from the English and Romanian adoptees study. *Journal of Abnormal Child Psychology, 36*(7), 1057–1068. https://doi.org/10.1007/s10802-008-9232-x
1. Nelson, C. A., III, Zeanah, C. H., Fox, N. A., Marshall, P. J., Smyke, A. T., & Guthrie, D. (2007). Cognitive recovery in socially deprived young children: The Bucharest Early Intervention Project. *Science, 318*(5858), 1937–1940. https://doi.org/10.1126/science.1143921
1. Davis, E. P., Glynn, L. M., Schetter, C. D., Hobel, C., Chicz-Demet, A., & Sandman, C. A. (2007). Prenatal exposure to maternal depression and cortisol influences infant temperament. *Journal of the American Academy of Child & Adolescent Psychiatry, 46*(6), 737–746. https://doi.org/10.1097/chi.0b013e318047b775
1. Burke, J. D., Pardini, D. A., & Loeber, R. (2008). Reciprocal relationships between parenting behavior and disruptive psychopathology from childhood through adolescence. *Journal of Abnormal Child Psychology, 36*(5), 679–692. https://doi.org/10.1007/s10802-008-9219-7
1. Cummings, E. M., Goeke-Morey, M. C., & Papp, L. M. (2004). Everyday marital conflict and child aggression. *Journal of Abnormal Child Psychology, 32*(2), 191–202. https://doi.org/10.1023/B:JACP.0000019770.13216.be
1. McDonough, M. H., Jose, P. E., & Stuart, J. (2016). Bi-directional effects of peer relationships and adolescent substance use: A longitudinal study. *Journal of Youth and Adolescence, 45*(8), 1652–1663. https://doi.org/10.1007/s10964-015-0355-4
1. Bonanno, R. A., & Hymel, S. (2013). Cyber bullying and internalizing difficulties: Above and beyond the impact of traditional forms of bullying. *Journal of Youth and Adolescence, 42*(5), 685–697. https://doi.org/10.1007/s10964-013-9937-1
1. Chung, H. L., & Steinberg, L. (2006). Relations between neighborhood factors, parenting behaviors, peer deviance, and delinquency among serious juvenile offenders. *Developmental Psychology, 42*(2), 319–331. https://doi.org/10.1037/0012-1649.42.2.319
1. Collishaw, S., Pickles, A., Messer, J., Rutter, M., Shearer, C., & Maughan, B. (2007). Resilience to adult psychopathology following childhood maltreatment: Evidence from a community sample. *Child Abuse & Neglect, 31*(3), 211–229. https://doi.org/10.1016/j.chiabu.2007.02.004
1. Conduct Problems Prevention Research Group. (2011). The effects of the fast track preventive intervention on the development of conduct disorder across childhood. *Child Development, 82*(1), 331–345. https://doi.org/10.1111/j.1467-8624.2010.01558.x

# Academic Honesty and Misconduct {#academicHonesty}

All students in CLAS courses are expected to abide by the [CLAS Code of Academic Honesty](https://clas.uiowa.edu/students/handbook/academic-fraud-honor-code).
Academic misconduct must be reported by instructors to CLAS according to [these procedures](https://clas.uiowa.edu/students/handbook/academic-fraud-honor-code).
Please note that collaboration with other classmates on quizzes and during exams is not permitted.
However, I do encourage you to collaborate with classmates to *prepare* for exams (e.g., informal study groups).
Because writing, analytical, and critical thinking skills are part of the learning outcomes of this course, all work submitted by students should be prepared by the student.
Developing strong competencies in these domains will prepare you for a competitive workplace.
Therefore, AI-generated submissions are not permitted and will be treated as plagiarism.

# Course Requirements and Policies {#requirements}

## Lecture {#lecture}

We will meet three times weekly for lectures, at the time and location described [above](#lectureTime).
My powerpoint presentations for the lectures will be posted on [ICON](https://icon.uiowa.edu) no later than noon on the day before the lecture (though I may continue to refine the slides up until the time of lecture).
<u>Please note:</u> powerpoint presentations are an outline of my points. 
<u>It is your responsibility to take notes during class.</u>
If you have questions about the lecture notes or need clarification of any of the points, please ask in class or meet with the TA or Professor Petersen during office hours. 
If you miss class and/or need help catching up on the notes, please make an appointment with the TA.

## Attendance and Participation {#attendanceParticipation}

Attendance at lectures is required and will be checked and factored into final grades (see grading section [below](#grading)).
There are 43 lectures during the semester (excluding examinations).
You will receive one point for attendance at each lecture up to 40 points (i.e., you will not receive extra credit for attending all 43 lectures).
<u>Thus, you will not be penalized for missing up to 3 lectures.
However, you will be responsible for learning any material missed for quizzes and exams, and I strongly encourage you to attend all lectures.
Poor lecture attendance is likely to affect the quality of students' work and success in the course.</u>

Students who miss <u>more than 3 lectures</u> due to participation in University activities must give the instructor a statement <u>before the absence</u> signed by a responsible official that specifies the dates and times the student will miss class.
Authorized activities include participation in athletic teams, the marching band or pep band, debate teams, and other recognized University groups, as well as participation in University field trips, service with the National Guard, and jury duty.
Absences due to illnesses or emergencies (that go over 3 lectures) must be documented with the University of Iowa [Absence Explanation Form](https://clas.uiowa.edu/faculty/student-attendance-and-absences) and sent to the TA within 48 hours of the absence.
Per university policy, if a student will be absent <u>5 or more consecutive days and the absence is due to illness or other emergency</u>, please contact the Registrar Service Center at (319) 384-4300 or registrar@uiowa.edu.

## Readings {#readings}

Readings from your text are assigned by lecture topic.
You should read and take notes on the material before class.
Past experience has shown that to do well in this class you should read the assigned material, attend lectures and take notes, and review your notes each week.
There is too much material being covered in this class to try to study only by frantic preparation immediately before quizzes and exams.

## Workload {#workload}

This is a 3 semester hour course.
Students should therefore expect to spend [6 additional hours per week](https://clas.uiowa.edu/faculty/student-workload-guidelines) (outside of class) reading the textbook and articles, reviewing lecture material, preparing for quizzes and exams, and completing writing assignments.

## Quizzes {#quizzes}

Six quizzes will be administered via the [ICON](https://icon.uiowa.edu) website.
Students <u>are</u> allowed to use their textbook and lecture notes on the quizzes.
However, students <u>may not</u> work together on the quizzes.
<u>Questions will be randomized and presented such that students must answer one question at a time (i.e., students may not go back to a previous question in the quiz).</u>
Quizzes will consist of approximately 20–30 multiple choice or very short answer questions.
Although students may take the quiz at any time when it is available, students must complete the quiz within <u>2 hours</u>. 
We will not accept late responses or multiple submissions.
Your lowest quiz score will be dropped.
We will not accept excused absences for quizzes because (a) you have a week to complete the quiz (and can submit it at any point during that week), and (b) we drop your lowest quiz score.
Each quiz will be weighted the same in the final grade.

Although students will have access to their course materials during the quiz, reading and advanced preparation will be necessary to do well on the quizzes.
<u>Material for quiz questions will be taken from required readings (texts and articles) as well as from lecture material.</u>
Quiz due dates and topics will be announced in class and via email and are listed below.
All quizzes should be submitted to [ICON](https://icon.uiowa.edu) by 11:59 p.m. on the due date.

| Quiz # | Dates Available | Topics Covered                                                 |
|--------|-----------------|----------------------------------------------------------------|
| 1      | 9/4 – 9/11      | History/D&P Model, Theories & Causes, Research with Children   |
| 2      | 9/22 – 9/29     | ADHD, ASD, Intellectual Disability, Specific Learning Disorder |
| 3      | 10/20 – 10/27   | CD, Anxiety, Depression, Bipolar, DMDD                         |
| 4      | 11/1 – 11/8     | Elimination, Eating, Substance-Related Disorders, Self-Injury  |
| 5      | 11/15 – 11/29   | Maltreatment and Resilience                                    |
| 6      | 12/1 – 12/8     | Levels of Analysis Articles, Prevention                        |

## Examinations {#exams}

There will be 2 exams; one mid-term exam and one non-cumulative final exam.
Each exam will emphasize information presented for the half of the class that precedes it.
However, some integration of information across sections will be required for questions on the final exam.
Exams will consist of short-answer and multiple choice questions based upon both readings (texts and articles) and the lecture material.
Exam dates are listed below.

**Exam 1 (Mid-Term Exam):	Wednesday, October 4, 2023 during class**\
**Exam 2 (Final Exam): TBD during finals week** (the date, time, and location will be announced by the 5th week of class by the College of Liberal Arts and Sciences)

### Missing Exams {#missingExams}

Students are allowed to make up exams that have been missed due to illness, mandatory religious observations, official University activities, or other unavoidable circumstances.
Note: the format of the make-up exam may differ from the original exam.
If you know that you must be away at the time of an exam for one of these reasons, Professor Petersen or the TA must be contacted in advance whenever possible to schedule a make-up exam.
In order to take a make-up exam, you must provide acceptable documentation to be eligible to take it: including documentation for any report of illness; any other circumstances must be documented by the University of Iowa [Absence Explanation Form](https://clas.uiowa.edu/faculty/student-attendance-and-absences) and must be approved by Professor Petersen.
<u>In sum, to be eligible for a make-up exam, Professor Petersen or the TA must be contacted before the examination whenever possible, and you must send acceptable form of documentation to Professor Petersen or the TA</u>.

## Literature Critiques {#litCritiques}

You will be required to complete two literature critique assignments.
These assignments are designed to help you learn to critically analyze original source articles in written form.
Both assignments involve providing a critique of a research article (Ra et al., 2018 – Article #2, and Christakis et al., 2004 – Article #3).
Both papers should be 2–3 pages long (double-spaced, APA format, 12-point Times New Roman font) and will be turned in via [ICON](https://icon.uiowa.edu).
Each should be in essay form and carefully proofread for spelling and grammatical errors.
<u>Students may not work together on the critiques.</u>
More information on how to structure the critiques will be provided in class.
Note: Turnitin will be used via [ICON](https://icon.uiowa.edu) to check for plagiarism of a fellow student and from the internet.
**The critiques are due on Monday, August 28 and Friday, September 8 by 11:59 p.m.**

## Literature Review {#litReview}

You will be required to write a <u>literature review</u> on a topic related to child psychopathology.
The topic of the paper is completely up to the student; the only requirement is that it must be relevant to psychopathology in children or adolescents.
The paper must include a review and analysis of at least 5 empirical articles on the topic, published since 2000.
You are encouraged to work with the [UI Writing Center](https://writingcenter.uiowa.edu) in revising your paper.

### Format {#litReviewFormat}

The paper should have five sections:

1. Cover Letter, described [here](#stage6)
1. Title Page
1. Abstract
1. Main body
1. References

The main body of the paper should be <u>10–12 pages</u>, excluding the cover letter, title page, abstract, and references.
The text should be double-spaced, in [APA format](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/index.html), and in 12-point Times New Roman font.
For sample papers in APA format, see [here](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/apa_sample_paper.html).

### Stages {#stages}

#### Overview {#stagesOverview}

This paper will be completed in 6 stages, all uploaded to [ICON](https://icon.uiowa.edu):

1. [Generate a topic](#stage1)
1. [Identify articles](#stage2)
1. [Understand findings from articles](#stage3)
1. [Write a complete draft](#stage4)
1. [Give and receive feedback](#stage5)
1. [Incorporate feedback and polish writing](#stage6)

The goals of this project are for each student to produce a thoughtful paper that describes an aspect of this course that captured their interest and to gain more experience with scientific writing.
Each stage of the process will be discussed in class, so attendance is critical.
Additionally, grading rubrics for each stage will be posted so that students understand the basis for evaluation of each stage of the assignment.
Successful completion of this assignment requires students to adhere closely to the deadlines outlined.
<u>For this reason, substantial penalties will be applied to all late work (20% off final grade for each day the assignment is late).
Further, to make sure the peer review process for first drafts is successful, any first drafts submitted after the deadline of Friday, November 3 will receive a zero and will not receive a peer review (the student will still receive instructor feedback).
If you have concerns about meeting one of the literature review deadlines, please contact Professor Petesen or the TA as soon as possible to discuss.</u>
All assignments should be uploaded to [ICON](https://icon.uiowa.edu) by 11:59 p.m. on the due date.

The stages—and deadlines—are described below:

#### Deadlines {#deadlines}

The workflow of the literature review stages, their respective percentages in the total literature review grade, and relevant due dates are listed below.

| Stage | Assignment Description | Percent | Due Date |
|-------|------------------------|---------|----------|
| 1     | **Develop a topic description (2 sentences) and 3–5 keywords** you will then use to conduct a literature search using [Google Scholar](http://purl.lib.uiowa.edu/GoogleSch), [PsycINFO](http://purl.lib.uiowa.edu/apa/psycinfo), and/or [PubMed](http://purl.lib.uiowa.edu/nlm/pubmed). | 2.5% | 9/15  |
| 2     | **Identify and generate a list of 5 empirical articles** that you will include in your review based on your searches of [Google Scholar](http://purl.lib.uiowa.edu/GoogleSch), [PsycINFO](http://purl.lib.uiowa.edu/apa/psycinfo), and/or [PubMed](http://purl.lib.uiowa.edu/nlm/pubmed).    | 2.5% | 9/25  |
| 3     | **Write brief summaries** of each of the 5 empirical articles that includes clear descriptions of both the methodology and relevant findings. | 10%  | 10/16 |
| 4     | **Compose a complete first draft** of the review that includes an introduction with thesis, description, critique, and integration of the 5 empirical studies. | 25%  | 11/3  |
| 5a    | Peer reviews are assigned. | –  | 11/6 |
| 5b    | **Give feedback** by providing anonymous peer review of another student's paper. | 10%  | 11/27 |
| 5c    | **Receive feedback** from peer and from instructor. | – | 11/29 |
| 6     | **Incorporate feedback and produce a final document.** | 50%  | 12/8  |

#### Stage 1: Generate a Topic {#stage1}

You will first develop a topic and a set of keywords for your paper.
For the review format, this involves generating a specific topic and keywords you will then use to conduct a literature search using [Google Scholar](http://purl.lib.uiowa.edu/GoogleSch), [PsycINFO](http://purl.lib.uiowa.edu/apa/psycinfo), and/or [PubMed](http://purl.lib.uiowa.edu/nlm/pubmed).
We will discuss strategies for generating topics and keywords in class, and examples will be provided.
<u>By the [deadline](#deadlines), you will turn in a summary of your research topic (1–2 sentences) and a list of keywords that will start your literature search</u>.

#### Stage 2: Identify Articles {#stage2}

After your topic has been approved, you will then conduct a search to identify the articles for your paper.
You will search PsychINFO or PubMed and identify a minimum of five empirical articles that are all relevant to your topic.
As we will discuss in class, it is important to define your topic carefully so that all of your identified articles are addressing common components.
<u>By the [deadline](#deadlines), you will turn in your list of articles</u>. 

#### Stage 3: Understand Findings from Articles {#stage3}

Once you have identified the five papers you wish to write about, you will then produce brief summaries of each article that include a description of the methods employed by the researchers and their basic findings (2–4 paragraphs per article for each of your five articles).
You will also include your reference list, in APA style.
<u>By the [deadline](#deadlines), you will turn in your article summaries</u>.

#### Stage 4: Write a Complete Draft {#stage4}

Next, you will write and turn in a complete draft of your paper.
The systematic review should include both description of the empirical studies you've included as well as analysis, critique, and integration of findings.
For this stage, you will also generate a thesis that describes the overall message of your review and you will work to demonstrate how each article is (or is not) supportive of your thesis.
The goal of this stage is to develop your ideas and argument so that you can receive feedback.
<u>By the [deadline](#deadlines), you will turn in your first draft of the paper.
Note: you must turn in a complete draft of your paper—not an outline.</u>

#### Stage 5: Give and Receiving Feedback {#stage5}

Following submission of your first draft, all students will receive detailed feedback from the instructor, which will include critique of content, organization, and argument.
Additionally each student will complete an anonymous peer review of a fellow student's paper (your draft will also be peer reviewed).
Peer reviews will be blinded and only I (the instructor) will know which papers belong to which students.
Reviews will be assigned in class.
More details about providing an appropriate review and the formatting will be provided in class.
<u>By the [deadline](#deadlines), you will turn in your review of the peer's paper.</u>
The instructor will then re-distribute the peer reviews to authors.  

#### Stage 6: Incorporating Feedback and Polishing Writing {#stage6}

You will receive comments from the instructor and from your peer reviewer via email.
You will then use these comments to revise your paper.
Your final paper must include a <u>cover letter</u> that details the changes you made to your draft based on feedback from the instructor as well as from your peer reviewer.
<u>Additionally, students are encouraged to meet with the TA during the week of November 27 to review their feedback and discuss plans for revision.</u>
<u>By the [deadline](#deadlines), you will submit the literature review</u>.
The literature review should include the manuscript itself as well as a cover letter describing the changes made in response to comments from the instructor and the peer reviewer.

# Grading {#grading}

Final grades will be assigned at the end of the semester on the basis of your total percentage of points earned on quizzes, examinations, written assignments, and lecture attendance, as detailed below.
Grades will be assigned on an absolute scale (criterion-referenced grading; see below); course grades will not be curved.
No extra-credit opportunities are available for this course.
Please note: As a matter of fairness to all students, I assign grades based on performance and do not negotiate grades.
Additionally, a penalty of 20% per day will be applied to all assignments turned in late.
Final grades will be assigned based on the following ranges:

| Grade | Percent |
|:------|:--------|
| A+    | 97–100% |
| A     | 93–96   |
| A-    | 90–92   |
| B+    | 87–89   |
| B     | 83–86   |
| B-    | 80–82   |
| C+    | 77–79   |
| C     | 73–76   |
| C-    | 70–72   |
| D+    | 67–69   |
| D     | 63–66   |
| D-    | 60–62   |
| F     | 0–59    |

I round up from .5 when determining final grades.
For example, a course percent of 79.50 would receive a B-, whereas a course percent of 79.49 would receive a C+.

The relative contribution of each component to your final grade is as follows:

- 5%    [Lecture Attendance](#attendanceParticipation)
- 10%   [Literature Critiques](#litCritiques) (2 at 5% each)
- 20%   [Exam 1](#exams) (Mid-Term)
- 20%   [Exam 2](#exams) (Final)
- 15%   [Quizzes](#quizzes) (5 quizzes after dropping lowest quiz score, 3% each)
- 30%   [Literature Review](#litReview)

# Tentative Course Outline (exam dates fixed) {#outline}

| Date        | Topic                                                 | Reading                  | Assignment Due                         |
|:------------|:------------------------------------------------------|:-------------------------|:---------------------------------------|
| 8/21        | History of Child Psychopathology                      | MWW Ch. 1                |                                        |
| 8/23        | Developmental Psychopathology                         | MWW Ch. 1; Article 1     |                                        |
| 8/25        | Theories & Causes                                     | MWW Ch. 2; Article 2     |                                        |
| 8/28        | Theories & Causes                                     | MWW Ch. 2                | **Critique 1 Due (Article 2)**         |
| 8/30        | Research with Children                                | MWW Ch. 3; Article 3     |                                        |
| 9/1         | *Conducting a Literature Search*                      |                          |                                        |
| 9/4         | **No Class – Labor Day**                              |                          | **Quiz 1 Opens**                       |
| 9/6         | DSM Assessment & Diagnosis                            | MWW Ch. 4                |                                        |
| 9/8         | Attention-Deficit Hyperactivity Disorder              | MWW Ch. 8                | **Critique 2 Due (Article 3)**         |
| 9/11        | Attention-Deficit Hyperactivity Disorder              | MWW Ch. 8                | **Quiz 1 Closes**                      |
| 9/13        | Attention-Deficit Hyperactivity Disorder              | MWW Ch. 8; Article 4     |                                        |
| 9/15        | Autism Spectrum Disorders                             | MWW Ch. 6                | **Topic and Keywords Due**             |
| 9/18        | Autism Spectrum Disorders                             | MWW Ch. 6                |                                        |
| 9/20        | Autism Spectrum Disorders/*Writing Article Summaries* | MWW Ch. 6; Article 5     |                                        |
| 9/22        | Intellectual Disability                               | MWW Ch. 5                | **Quiz 2 Opens**                       |
| 9/25        | **Research Day – Work on Paper**                      |                          | **List of Articles Due**               |
| 9/27        | Intellectual Disability/Learning Disorders            | MWW Ch. 5                |                                        |
| 9/29        | Learning Disorders                                    | MWW Section 7.4 ("Specific Learning Disorder") through the end of the chapter | **Quiz 2 Closes**                      |
| 10/2        | Catch-Up and Exam Review                              |                          |                                        |
| 10/4        | **MIDTERM EXAM IN CLASS**                             |                          |                                        |
| 10/6        | Conduct Problems                                      | MWW Ch. 9                |                                        |
| 10/9        | Conduct Problems                                      | MWW Ch. 9; Article 6     |                                        |
| 10/11       | *Writing a Literature Review*                         | Article 7                |                                        |
| 10/13       | Anxiety Disorders                                     | MWW Ch. 11               |                                        |
| 10/16       | Anxiety Disorders                                     | MWW Ch. 11               | **Article Summaries Due**              |
| 10/18       | Anxiety Disorders                                     | MWW Ch. 11; Article 8    |                                        |
| 10/20       | Depression                                            | MWW Ch. 10               | **Quiz 3 Opens**                       |
| 10/23       | Depression                                            | MWW Ch. 10               |                                        |
| 10/25       | Bipolar Disorder/DMDD                                 | MWW Ch. 10; Article 9    |                                        |
| 10/27       | Elimination/Feeding Disorders                         | MWW Section 13.3: ("Elimination Disorders", "Enuresis", and "Encopresis"); MWW Ch. 14 | **Quiz 3 Closes**                      |
| 10/30       | Eating Disorders                                      | MWW Ch. 14               |                                        |
| 11/1        | Eating Disorders                                      | Article 10               | **Quiz 4 Opens**                       |
| 11/3        | Substance Use and Risk-Taking                         | MWW Section 13.5 ("Adolescent Substance-Use Disorders") through the end of the chapter | **1st Draft Due**                      |
| 11/6        | Suicide and Self-Injury                               | Article 11               | **Peer Reviews Assigned**              |
| 11/8        | Child Maltreatment & Trauma                           | MWW Ch. 12               | **Quiz 4 Closes**                      |
| 11/10       | Child Maltreatment & Trauma                           | MWW Ch. 12               |                                        |
| 11/13       | Child Maltreatment & Trauma                           | Articles 12 & 13         |                                        |
| 11/15       | Individual Differences                                | Article 14               | **Quiz 5 Opens**                       |
| 11/17       | Parenting                                             | Article 15               |                                        |
| 11/20–11/24 | **FALL BREAK – NO CLASSES**                           |                          |                                        |
| 11/27       | Divorce and Marital Conflict                          | Article 16               | **Peer Review Due**                    |
| 11/29       | Peer Relationships & Bullying                         | Articles 17 & 18         | **Quiz 5 Closes**; **Receive Reviews** |
| 12/1        | Neighborhood Factors                                  | Article 19               | **Quiz 6 Opens**                       |
| 12/4        | Resilience                                            | Article 20               |                                        |
| 12/6        | Prevention Science                                    | Article 21               |                                        |
| 12/8        | Catch-Up/Final Exam Review in Class                   |                          | **Quiz 6 Closes**; **Final Paper Due** |
| 12/8        | **FINAL PAPER DUE**                                   |                          |                                        |
|             | **FINAL EXAM TBD (Week of 12/11–12/15)**              |                          |                                        |

# Date and Time of the Final Exam {#finalExam}

The final examination date and time will be announced by the Registrar generally by the fifth week of classes and it will be announced on the course ICON site once it is known.
<u>Do not plan your end of the semester travel plans until the final exam schedule is made public.
It is your responsibility to know the date, time, and place of the final exam.</u>
According to Registrar's final exam policy, students <u>have a maximum of two weeks after the announced final exam schedule</u> to request a change if an exam conflict exists or if a student has more than two exams in one day (see the [policy](https://registrar.uiowa.edu/makeup-final-examination-policies) here).

# Course Resources {#courseResources}

There are many course resources available to help you succeed in the class, including:

- the textbook and readings
- lectures and slides
- getting and reviewing missed notes from a peer
- TA office hours
- instructor office hours
- peer study groups
- the UI [Writing Center](https://writingcenter.uiowa.edu)
- Tutor Iowa: https://tutor.uiowa.edu

# Drop Deadline for this Course {#dropDeadline}

You may drop an individual course before the deadline; after this deadline you will need collegiate approval.
You can look up the [drop deadline for this course](https://registrar.uiowa.edu/course-deadlines) here.
When you drop a course, a "W" will appear on your transcript.
The mark of "W" is a neutral mark that does not affect your GPA.
Directions for adding or dropping a course and other registration changes can be found on the [Registrar's website](https://registrar.uiowa.edu/change-registration-myui).
Students can find policies on dropping and withdrawing [here](https://clas.uiowa.edu/students/students-academic-policies/registration-policies#dropping).

# Feedback about the Course {#feedback}

I welcome feedback at any point during the class.
If you have comments on the class or my teaching, please feel free to meet with me during office hours.

## Student Complaints {#complaints}

Students with a complaint about a grade or a related matter should first discuss the situation with the instructor, and finally with the Director or Chair of the school, department, or program offering the course.
Students should contact [CLAS Undergraduate Programs](https://clas.uiowa.edu/students/handbook/student-rights-responsibilities#rights) for support when the matter is not resolved at the previous level.

# Communication: UI Email {#email}

Students are responsible for all official correspondences sent to their UI email address (uiowa.edu) and must use this address for any communication with instructors or staff in the UI community.
For the privacy and the protection of student records, UI faculty and staff can only correspond with UI email addresses.

# Health and Safety {#health}

The University of Iowa strongly encourages students, faculty, and staff to be vaccinated against COVID-19.
For information about COVID-19 vaccines on campus, please see https://coronavirus.uiowa.edu.
If you are feeling sick, test positive for COVID-19, or may have been exposed to COVID-19, please refer to the campus guidance for the appropriate action (https://coronavirus.uiowa.edu/returning-campus/showing-symptoms).
Regardless of your vaccination status, if you have symptoms consistent with COVID-19, please stay home and follow the appropriate isolation/quarantine guidance.
For up-to-date information throughout the semester, please refer to https://coronavirus.uiowa.edu.

# College of Liberal Arts and Sciences (CLAS) Course Policies {#clasPolicies}

- [Attendance and Absences](https://clas.uiowa.edu/faculty/student-attendance-and-absences)\
[University regulations require that students be allowed to make up examinations](https://opsmanual.uiowa.edu/students/absences-class) that have been missed due to illness, religious holy days, military service obligations (including service-related medical appointments), or other unavoidable circumstances or University-sponsored activities.
See the section above on "[Missing Exams](#missingExams)" for the documentation necessary for an absence to be excused and to be eligible to take a make-up exam.
Students with UI-authorized activities must discuss their absences with the instructor or TA as soon as possible.
Religious obligations must be communicated within the first three weeks of classes.

## Other Expectations of Student Performance {#otherExpectations}

Students have the right to a distraction-free learning environment.
You have the responsibility to help create such a classroom environment.
Please treat other students in the class, the TAs, and the instructor with respect.
Students are expected to help each other learn and to contribute overall to the learning environment of the course.
Arriving prepared for class is part of this expectation.

# University Policies {#UIowaPolicies}

[Accommodations for Students with Disabilities](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#accommodations-for-students-with-disabilities)\
The University is committed to providing an educational experience that is accessible to all.
If a student has a diagnosed disability or other disabling condition that may impact the student's ability to complete the course requirements as stated in the syllabus, the student may seek accommodations through [Student Disability Services](https://sds.studentlife.uiowa.edu/students) (SDS).
SDS is responsible for making Letters of Accommodation (LOA) available.
The student must provide an LOA to the instructor as early in the semester as possible, but requests not made at least two weeks prior to the scheduled activity for which an accommodation is sought may not be accommodated.
The LOA will specify what reasonable course accommodations the student is eligible for and those the instructor should provide. Additional information can be found on the [SDS website](https://sds.studentlife.uiowa.edu/students/apply).

- [Classroom Expectations](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#classroom-expectations)
- [Free Speech and Expression](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#free-speech-and-expression)
- [Non-discrimination](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#non-discrimination-statement)
- [Absences for Religious Holy Days](https://opsmanual.uiowa.edu/students/absences-class#8.2)
- [Sexual Harassment/Misconduct and Supportive Measures](https://provost.uiowa.edu/teaching-resources/course-syllabi-information#sexual-harassment--sexual-misconduct-and-supportive-measures)

# Where to Get Academic Support for This Course {#academic-support}

- Drop-in study groups and one-on-one tutoring: drop-in student hours of the TA and instructor
- Formal tutoring: Tutor Iowa: https://tutor.uiowa.edu
- UI Writing Center: https://writingcenter.uiowa.edu
- Academic accommodations: https://sds.studentlife.uiowa.edu

# Mental Health Resources and Student Support {#mental-health}

Students are encouraged to be mindful of their mental health and seek help as a preventive measure or if feeling overwhelmed and/or struggling to meet course expectations.
Students are encouraged to talk to their instructor for assistance with specific class-related concerns.
For additional support and counseling, students are encouraged to contact University Counseling Service (UCS).
Information about UCS, including resources and how to schedule an appointment, can be found at [counseling.uiowa.edu](http://counseling.uiowa.edu).
Find out more about UI mental health services at [mentalhealth.uiowa.edu](http://mentalhealth.uiowa.edu).

[Student Care and Assistance](https://dos.uiowa.edu/assistance) provides assistance to University of Iowa students who are experiencing a variety of crisis and emergency situations, including but not limited to medical issues, family emergencies, unexpected challenges, and sourcing basic needs such as food and shelter.
More information on the resources related to basic needs can be found at [basicneeds.uiowa.edu/resources](https://basicneeds.uiowa.edu/resources).
Students are encouraged to contact Student Care & Assistance in the Office of the Dean of Students (Room 135 IMU, [dos-assistance@uiowa.edu](dos-assistance@uiowa.edu), or 319-335-1162) for support and assistance with resources.

If you feel that you or someone you know may be struggling with an academic, emotional, or psychological problem, the following organizations are available for assistance:

| Service                                                                    | Contact Info                                                     |
|:---------------------------------------------------------------------------|:-----------------------------------------------------------------|
| University of Iowa Academic Advising Center                                | 353-5700, https://advisingcenter.uiowa.edu                       |
| University Counseling Services                                             | 335-7294, https://www.uiowa.edu/ucs                              |
| Student Health Service - Mental Health                                     | 335-8394, https://studenthealth.uiowa.edu/services/psychiatry    |
| University of Iowa Hospitals and Clinics Adult Psychiatry Services Clinic  | 353-6314, https://www.uihealthcare.org/Psychiatry                |
| Seashore Clinic (in the UI Department of Psychological and Brain Sciences) | 335-2467, https://psychology.uiowa.edu/resources/seashore-clinic |
| Women's Resource and Action Center                                         | 335-1486, https://wrac.uiowa.edu                                 |
| Rape Victim Advocacy Program                                               | 319-335-6000 or 800-228-1625, https://www.uiowa.edu/~rvap        |
| Office of Sexual Misconduct                                                | 319-335-6200, https://osmrc.uiowa.edu                            |
| CommUnity                                                                  | 855-325-4296, https://builtbycommunity.org/crisis                |
| Community & Family Resources                                               | 351-4357, https://www.cfrhelps.org/                              |

<u>If you or someone you know is contemplating suicide</u>, either call or text the Suicide and Crisis Lifeline at 988, or call 911.

# Disclaimer {#disclaimer}

This syllabus is subject to change.
Any changes will be discussed in class, via email, and/or on [ICON](https://icon.uiowa.edu).
